### ISSUE TITLE
財務系統 審核時間表

### ISSUE THREAD

**Issue by stevectopskyweb** [TopSkyWeb/PM_to_do_list#47]
## 資料參考：
https://docs.google.com/spreadsheets/d/1ZKjGj91V4d2IO3u59XYj8VELTRq2d8iimPh8Cq0Hdng/edit#gid=0
## 頁面需求：
篩選條件如下
1. 申請單建立時間區間
2. 審核-出款 時間相差 下拉式選項
   a. 7分鐘內 
   b. 7-15 分鐘
   c. 15- 25分鐘
   b. 25 分鐘以上
顯示欄位及內容如表單

## 進程：
- [x] wirframe
- [x] 頁面邏輯文件
- [x] 確認需求

**Comment by elsaaalin** [comment]
資料庫 uc read
資料表 sso_amount, sso_members
使用欄位 
sso_amount：id,uid, status, type, addtime, checktime, paidtime, info1
sso_members: id, username
區間定義: 美東時間 +4 ( uc資料庫12-1159)

以下為撈取四月份的 sql 範例 要轉為 orm 
select sso_amount.id ,sso_members.username, 
FROM_UNIXTIME( sso_amount.checktime, '%m/%d %H:%i') , FROM_UNIXTIME( sso_amount.paidtime, '%m/%d %H:%i'),
(sso_amount.paidtime - sso_amount.checktime)/60, #相差幾分鐘
sso_amount.info1  #出款卡
from sso_amount 
left join sso_members on sso_members.id = sso_amount.uid
where sso_amount.status = 2 #已經成立的
and sso_amount.type = 3 #出款
and sso_amount.addtime between UNIX_TIMESTAMP('2019-04-01 12:00:00') and UNIX_TIMESTAMP('2019-05-01 11:59:59') 
and sso_amount.paidtime - sso_amount.checktime >= 900

**Comment by stevectopskyweb** [comment]
Issue moved to [TopSkyWeb/system-ininder-laravel-admin #680](https://github.com/TopSkyWeb/system-ininder-laravel-admin/issues/680) via [**ZenHub**](https://www.zenhub.com/)
